# Generated by Django 4.0.2 on 2023-04-20 11:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeatCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', ckeditor.fields.RichTextField()),
                ('Weight', models.CharField(blank=True, max_length=50, null=True)),
                ('PCS', models.PositiveIntegerField()),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.meatcategories')),
            ],
        ),
    ]
