# Generated by Django 4.0.2 on 2023-04-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Meat_Image'),
        ),
    ]
