# Generated by Django 4.0.2 on 2023-04-21 08:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_meat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMCGCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FMCGSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FMCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpireDate', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('ManufactureDate', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Description', ckeditor.fields.RichTextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/FMCG_Image')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.fmcgcategories')),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.fmcgsubcategories')),
            ],
        ),
    ]
