# Generated by Django 4.0.2 on 2023-04-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_fmcgcategories_fmcgsubcategories_fmcg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmcg',
            name='ExpireDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fmcg',
            name='ManufactureDate',
            field=models.DateField(null=True),
        ),
    ]
