# Generated by Django 4.0.2 on 2023-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_fmcg_expiredate_alter_fmcg_manufacturedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmcg',
            name='ExpireDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fmcg',
            name='ManufactureDate',
            field=models.DateTimeField(null=True),
        ),
    ]
