# Generated by Django 4.0.2 on 2023-04-22 09:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_fmcg_expiredate_alter_fmcg_manufacturedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothesSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='fmcg',
            name='Image',
        ),
        migrations.AddField(
            model_name='fmcg',
            name='Image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/FMCG_Image'),
        ),
        migrations.AddField(
            model_name='fmcg',
            name='Image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/FMCG_Image'),
        ),
        migrations.AddField(
            model_name='fmcg',
            name='Image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/FMCG_Image'),
        ),
        migrations.AlterField(
            model_name='meat',
            name='Image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/Meat_Image'),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=20, null=True)),
                ('Size', models.CharField(blank=True, max_length=20, null=True)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('finalprice', models.FloatField()),
                ('stock', models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='In Stock', max_length=20, null=True)),
                ('Description', ckeditor.fields.RichTextField()),
                ('Image1', models.ImageField(blank=True, default='', null=True, upload_to='Images/Clothes_Image')),
                ('Image2', models.ImageField(blank=True, default='', null=True, upload_to='Images/Clothes_Image')),
                ('Image3', models.ImageField(blank=True, default='', null=True, upload_to='Images/Clothes_Image')),
                ('Image4', models.ImageField(blank=True, default='', null=True, upload_to='Images/Clothes_Image')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clothesbrand')),
                ('MainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clothescategories')),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clothessubcategories')),
            ],
        ),
    ]
