# Generated by Django 4.0.2 on 2023-04-24 03:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_clothesbrand_clothescategories_clothessubcategories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', ckeditor.fields.RichTextField()),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('ManufactureDate', models.DateTimeField(null=True)),
                ('ExpireDate', models.DateTimeField(null=True)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('finalprice', models.FloatField()),
                ('Storage', models.CharField(blank=True, max_length=200, null=True)),
                ('Uses', models.CharField(blank=True, max_length=200, null=True)),
                ('Benefits', models.CharField(blank=True, max_length=200, null=True)),
                ('SideEffects', models.CharField(blank=True, max_length=200, null=True)),
                ('How_to_use', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='In Stock', max_length=20, null=True)),
                ('Image1', models.ImageField(blank=True, default='', null=True, upload_to='Images/Medicine_Image')),
                ('Image2', models.ImageField(blank=True, default='', null=True, upload_to='Images/Medicine_Image')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.medicinebrand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.medicinecategory')),
            ],
        ),
    ]
