# Generated by Django 4.0.2 on 2023-04-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_medicinebrand_medicinecategory_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='ExpireDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ManufactureDate',
            field=models.DateField(null=True),
        ),
    ]
