# Generated by Django 4.0.2 on 2023-04-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_medicine_expiredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='MainCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.clothescategories'),
        ),
    ]
