# Generated by Django 4.0.2 on 2023-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_clothes_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmcg',
            name='FinalPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fmcg',
            name='Image4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/FMCG_Image'),
        ),
    ]
