# Generated by Django 4.0.2 on 2023-04-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_fmcg_finalprice_fmcg_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat',
            name='finalPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
