# Generated by Django 4.0.2 on 2023-04-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_fmcgbrand_fmcg_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmcg',
            name='stock',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='In Stock', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meat',
            name='stock',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='In Stock', max_length=20, null=True),
        ),
    ]
