# Generated by Django 4.0.2 on 2023-04-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_fmcg_stock_meat_stock'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='FMCGReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('fmcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.fmcg')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.clothes')),
            ],
        ),
    ]
